### ISSUE TITLE
April 8 Community Call - Qualitative Data Analysis w/ Beth Duckles

### ISSUE THREAD

**Issue by jules32** [Openscapes/how_we_work#136]
**Date:** April 8 2022
**Time:** 11-11:50am, Pacific Time
**Location:** Zoom, (via eventbrite registration)

## Overview

**A Qualitative Data Analysis Chat with Dr. Beth Duckles** Casual conversation with Beth to discuss QDA and evaluation.

Potential questions/ideas (to iterate and add!) 

- What is QDA? Where/how is it used?
- Describe process & results experimenting with Openscapes - can agendas be used to evaluate?
- What does Beth what to be sure to talk about? Storytelling? So many cool things

## Agenda

Times PT

- 9:45 - sign into Zoom to setup/check audio etc
- 9:55 - start rotating slides and letting people in Zoom
    - one slide says we'll start at at :02 after, say hello in Chat
- 10:00 - start pump up music, slides keep rotating
- 10:02 - welcome (Erin)
- 10:05 - Chat with Beth
- 10:40 - Participant Q&A (Julie curated)
- 10:45 - closing & thank you
- 10:50 - end

Examples of previous Openscapes Community Calls: https://www.openscapes.org/tags/community-call/

## TODO - @jules32

- [x] ask Beth for bio, description, & image for web (see next 2 items)
- [x] create page at https://openscapes.org/events
- [x] set up eventbrite page with registration, ~ March 21
- [x] tweet announcement ~March 21
- [x] tweet reminder ~April 4 & 7
- [x] ask Beth about her favorite pump-up song/a song she likes that we'll play at the intro
- [x] create slides

**Comment by jules32** [comment]
Hi Beth!

How does this announcement text and short bio sound to you: 

Please join us for "A Qualitative Data Analysis Chat with Dr. Beth Duckles". This will be a casual conversation with Beth to discuss qualitative data analysis - what it is and how it can be used for evaluation. [MORE?]

Dr. Beth Duckles is a research consultant and social scientist. She helps technologists, designers and scientists gather and use human-centered data, supporting folks who are trying out their mixed methods or qualitative skills and want coaching and partnership in conducting and analyzing their research. Beth is also the Founder and Co-Director of [Open Post Academics](https://openpostac.org/) (formerly the Athenas), an online peer-support community for people with a Ph.D. who have left or are considering leaving academia.

**Comment by jules32** [comment]
[Agenda doc](https://docs.google.com/document/d/1gbIRHNFjKCrQ5QNoT0jldQi9K8pY48Dkxcssro2D8wE/edit)

[Slides](https://docs.google.com/presentation/d/1Pp_yhiA1McX_pidit_00iwlAJaepqseX7Tqb7iBaNi4/edit#slide=id.gc55b224ab0_0_1)

cc: @erinmr

**Comment by jules32** [comment]
Woohoo! Thanks everyone!

Next steps: 
- [ ] upload recording to youtube
- [ ] draft blog

**Comment by jules32** [comment]
Next steps for @stefaniebutland (unless noted):

- [ ] review & complete blog draft at bottom of [Agenda doc](https://docs.google.com/document/d/1gbIRHNFjKCrQ5QNoT0jldQi9K8pY48Dkxcssro2D8wE/edit) 
- [ ] ping Beth for comments (Slack)
- [ ] create blogdown post, making a branch in [website repo](https://github.com/Openscapes/website/tree/main/content/blog)
- [ ] create PR
- [ ] Publish ~ April 28- @jules32

**Comment by jules32** [comment]
Hi @stefaniebutland , here is the YouTube link! https://youtu.be/ex4KVnWDMDQ

**Comment by stefaniebutland** [comment]
Fri Apr 22, Beth says she's reviewing draft post in doc asap.

**Comment by stefaniebutland** [comment]
PR: https://github.com/Openscapes/website/pull/24

**Comment by jules32** [comment]
Merged and Tweeted! https://twitter.com/openscapes/status/1519058603562639360

Thanks @stefaniebutland 🎉
