### ISSUE TITLE
Community Call  - intro to Quarto

### ISSUE THREAD

**Issue by jules32** [Openscapes/how_we_work#145]
**Date:** June 9 2022
**Time:** 3:30-5pm, Pacific Time
**Location:** Zoom, (via eventbrite registration)
[**PlanningDoc**](https://docs.google.com/document/d/1NH2_R9gJR06TiMAJbXrn3bpzCVYSpP2cvh581XIAYnw/edit#heading=h.1z2fvs9bwc6y)

## Overview

**Hello Quarto!** A Quarto Chat with NASA Openscapes, co-hosted with RLadies Santa Barbara

Please join us for a chat about [Quarto](http://quarto.org/) - What is it? What does it look like? How do you use it, what can it do? How does it compare to RMarkdown? What does it mean for Python and Jupyter Notebooks? What about for open science, reproducibility, interoperability, and publishing?

Folks from NASA Openscapes will share their experiences using Quarto to enable data-intensive open science on the cloud, in conversation with RLadies Santa Barbara. Following an hour of conversation, demoing, and community Q&A, we’ll have another 20 minutes of informal chat and breakout rooms. 

This event is co-hosted by [Openscapes](https://openscapes.org/) and [RLadies Santa Barbara](https://twitter.com/RLadiesSB).

## Agenda

TBD: 

- fully remote, on Zoom
- combining RLadies casual networking with Openscapes Community Call structure.
- maybe 1 hour community call then 30 mins casual chatting, breakout rooms available for people to move into themselves?

Examples of previous Openscapes Community Calls: https://www.openscapes.org/tags/community-call/

## TODO

- [x] plan timing with RLadiesSB - @stefaniebutland 
- [x] create page at https://openscapes.org/events ~May 11 @stefaniebutland 
- [x] set up eventbrite page with registration ~May 10 @jules32
- [x] tweet announcement ~May 11 @jules32 
- [x] slack announcement ~May11 @stefaniebutland 
- [x] add question prompts to doc ~May 15, Sam, An, Julie, Stef
- [x] coordinate with NASA Mentors - Julie
- [x] book pre-mtg w speakers @stefaniebutland 
- [x] tweet tagging speakers
- [x] fill out public doc for the call @stefaniebutland 
- [x] tweet reminder ~June 7 @jules32 
- [x] create intro slides @stefaniebutland 
- [ ] video to YouTube @jules32 
- [ ] blog post @stefaniebutland & Sam Csik
- [ ] tweet & Slack share blog post

**Comment by jules32** [comment]
Woohoo things for tomorrow look ready to go! I'll review again to practice tomorrow but super excited, thank you!

**Comment by jules32** [comment]
A really fantastic event. 

110 people registered, 60 attended. 

Seemed like just the right amount of practice and planning; each speaker was able to share their perspective and had a bit of time for organic responses and screensharing. I learned from each person, so neat to hear in their own words what they learned. For me, so cool to try out the citations for the first time live with J.J. and Mine directing. Sam Csik is a fab interviewer! 

Closing, blog post progess here: https://github.com/Openscapes/how_we_work/issues/160
