### ISSUE TITLE
Community Call - how to kyber your workflow March 28

### ISSUE THREAD

**Issue by stefaniebutland** [Openscapes/how_we_work#217]
**Date:** Tuesday, March 28, 2023
**Time:** 10:00 - 11:00 am Pacific Time
**Location:** Zoom, (via eventbrite registration)

## Agenda

Example times (PT)

- 9:45 - sign into Zoom to setup/check audio etc
- 9:55 - start rotating slides and letting people in Zoom
	- one slide says we'll start at at :02 after, say hello in Chat
- 10:00 - start pump up music, slides keep rotating
- 10:02 - welcome (Stef)
- 10:05 - kyber (Sean Kross)
- 10:30 - Audience Q & A
- 10:50 - closing & thank you
- 10:55 - end

Examples of previous Openscapes Community Calls: https://www.openscapes.org/tags/community-call/

## TODO

In the checklist below, DATE is placeholder for deadline, to be filled in.

- [x] create draft Google Doc for event 
- [x] set up eventbrite page with registration, zoom link DATE
- [x] create page at https://openscapes.org/events
- [x] tweet announcement, DATE
- [x] planning meeting with Sean, Stef, Julie, Wed Mar 15
- [x] engage potential participants / stakeholders
- [x] tweet reminder DATE
- [x] ask Sean about his favorite pump-up song/a song he likes that we'll play at the intro
- [x] create intro slides
- [x] publish blog post

## Content

kyber motivation, demo use in Openscapes, discuss generalized applications / adaptations

**Comment by stefaniebutland** [comment]
post: https://openscapes.org/blog/2023/04/06/kyber/
