### ISSUE TITLE
Community Call: Coiled, Nov 28

### ISSUE THREAD

**Issue by stefaniebutland** [Openscapes/how_we_work#294]
**Date:** Tuesday, November 28, 2023
**Time:** 10:00 - 11:00 am PST
**Location:** Zoom, (try registration via Zoom this time)

## Agenda

Example times (PT)

- 9:45 - sign into Zoom to setup/check audio etc
- 9:55 - start rotating slides and letting people in Zoom
	- one slide says we'll start at at :02 after, say hello in Chat
- 10:00 - start pump up music, slides keep rotating
- 10:02 - welcome 
- 10:05 - Celebrity interview or panel with lightly structured conversations with short demos/screensharing
- 10:30 - Audience Q & A
- 10:50 - closing & thank you
- 10:55 - end

Examples of previous Openscapes Community Calls: https://openscapes.org/blog#category=community-call

## TODO

In the checklist below, DATE is placeholder for deadline, to be filled in.

- [x] create draft Google Doc for event 
- [x] set up eventbrite page with registration (try Zoom registration this time), zoom link; add zoom link to Google Invites & Doc (Zoom registration [link](https://zoom.us/meeting/register/tJMpdeuvpjMrEtbVNt5Sc1sCaxnnnlULwpXM))
- [x] create page at https://openscapes.org/events ([link](https://openscapes.org/events/2023-11-28-coiled-openscapes/))
- [x] add to https://nasa-openscapes.github.io/ upcoming events
- [x] toot announcement ([link](https://www.google.com/url?q=https://fosstodon.org/@openscapes/111417535048314812&sa=D&source=calendar&ust=1700528840875163&usg=AOvVaw34KCi5P_wwk020y8EGI43U))
- [x] planning meeting with speakers, Stef, Julie, Erin, Tues Nov 21, 10-10:55
- [x] engage potential participants / stakeholders
    - posted to Slacks: Openscapes, CSCCE, Standard Office Space, FTS - Friendly Tech Space 
- [ ] toot reminder DATE
- [ ] ask speakers about their favorite pump-up song/a song they like that we'll play at the intro
- [x] create intro slides
- [x] call takes place
- [x] update Event page - event past
- [ ] publish blog post & toot
- [ ] add post link to Event page

## Content

From Julie: Would be great for Amy/Luis/Andy to lead the demos building from their UWG presentation, in conversation with James

**Comment by jules32** [comment]
I created a calendar invite for Nov 28, 10-11 PT and added everyone from from the email thread. 

TODO for Stef: 

- [ ] add Zoom link to calendar invite (when time confirmed by Amy, Luis)

Great to try out Zoom registration for this! Thanks

**Comment by stefaniebutland** [comment]
[Google doc](https://docs.google.com/document/d/12iwOURQQ0qKwsTt37HL1M8gRcWgIg3TIREqY13p0s28/edit) for community call. Content to be updated

**Comment by stefaniebutland** [comment]
@erinmr @jules32 We're trying Zoom registration instead of Eventbrite (less work, same outcome imo). Do we want to ask any custom questions when they register? Something helpful like "what do you want to learn about Coiled or NASA-Openscapes?"


![Image](https://github.com/Openscapes/how_we_work/assets/11927811/4766c3b3-2748-4cd0-99cf-e304350d5f7f)

**Comment by jules32** [comment]
Thanks @stefaniebutland . I'm fine with no custom questions. Or, an optional custom question that says "tell us a bit about your interest in this community call topic" if we want to reuse for future community calls.

**Comment by stefaniebutland** [comment]
Yay for branding in Zoom registration


![Image](https://github.com/Openscapes/how_we_work/assets/11927811/69c0b668-2339-4792-8189-bd9e38e7ad18)

**Comment by stefaniebutland** [comment]
Event page WIP [draft PR](https://github.com/Openscapes/website-new/pull/70); tagged Julie

**Comment by jules32** [comment]
Thanks Stef, just approved!

**Comment by stefaniebutland** [comment]
Event page is up. Participants must register via Zoom (linked on event page) [Openscapes Community Call: NASA Earthdata Cloud with Coiled](https://openscapes.org/events/2023-11-28-coiled-openscapes/)

**Comment by jules32** [comment]
Stef, the time on the website is 2 hours, is that correct?

**Comment by stefaniebutland** [comment]
fixed. thanks Julie!!

**Comment by jules32** [comment]
I drafted a quick first pass to the blog post, suggesting we publish Dec 7
