### ISSUE TITLE
Community Call: Openscapes Goes to the White House

### ISSUE THREAD

**Issue by stefaniebutland** [Openscapes/how_we_work#382]
We can use this issue to add updates as we plan.

**Proposed Date:** Thursday, September 26, 2024
**Proposed Time:** 1:00 - 2:00 pm PT /  4:00 - 5:00 pm ET / 10:00 - 11:00 am HT ([find your timezone](https://www.timeanddate.com/worldclock/fixedtime.html?msg=Community+Call%3A+Openscapes+Goes+to+the+White+House&iso=20240926T13&p1=1050&ah=1))
**Location:** Zoom, (via [zoom registration](https://zoom.us/meeting/register/tJwvce2grzwsHtY5fAG5DWmp2m3wOw0T9_6q))

## Speakers
Julie Lowndes, Ileana Fenwick; maybe a mutual interview could be cool - ask each other the questions

## Topic
Open science adventures in Washington DC, September 2024: 1) Ileana & Julie attending and Julie is invited panelist at Dynamic Convergence workshop; 2) Openscapes invited to White House  OSTP.

Sharing the excitement, emotions, hard work over years building up to this "overnight success" ;-) , why was Openscapes invited (challenge.gov), who else was there, how did you prepare, what were your big asks. In light of YOS OSTP fact sheet, note that Openscapes Mentors like Eli Holmes, NMFS Open Science, & Jeff Hollister, US EPA, are OSTP reps.

## Links & Resources
- Openscapes post: [Biden-Harris Administration announces support for NOAA Fisheries’ data, infrastructure, and workforce modernization in part via Openscapes](https://openscapes.org/blog/2024-08-19-biden-harris-noaa-fisheries/)
- NOAA Fisheries announcement Aug 15, 2024: [Biden-Harris Administration Announces $34 Million to Modernize NOAA Fisheries’ Data, Infrastructure and Workforce](https://www.fisheries.noaa.gov/media-release/biden-harris-administration-announces-34-million-modernize-noaa-fisheries-data)
- Openscapes post: [White House Fact Sheet Mentions Openscapes!](https://openscapes.org/blog/2024-02-09-white-house-factsheet-openscapes/)
- [FACT SHEET: Biden-⁠Harris Administration Marks the Anniversary of OSTP’s Year of Open Science](https://www.whitehouse.gov/ostp/news-updates/2024/01/31/fact-sheet-biden-harris-administration-marks-the-anniversary-of-ostps-year-of-open-science/), Jan 31, 2024

## Agenda

Example times (PT)

- 9:45 - sign into Zoom to setup/check audio etc
- 9:55 - start rotating slides and letting people in Zoom
	- one slide says we'll start at at :02 after, say hello in Chat
- 10:00 - start pump up music, slides keep rotating
- 10:02 - welcome 
- 10:05 - Celebrity interview or other speaker content
- 10:30 - Audience Q & A
- 10:50 - closing & thank you
- 10:55 - end

Examples of previous Openscapes Community Calls: https://www.openscapes.org/tags/community-call/

## TODO

In the checklist below, DATE is placeholder for deadline, to be filled in.

- [x] set up [zoom registration](https://openscapes.github.io/approach-guide/approach/tooling.html#zoom)
- [x] create page at https://openscapes.org/events
- [x] create draft Google Doc for event 
- [x] add zoom registration link to Google Invites & Doc
- [x] promo announcement via Slacks, Mastodon, Bluesky
- [x] engage potential participants / stakeholders
- [x] planning meeting with speakers, Stef, Julie, 1-week prior to event
- [x] Reminders
  - [x]  Slack, Mastodon, Bluesky
  - [x]  [Zoom reminder email](https://openscapes.github.io/approach-guide/approach/tooling.html#zoom) to registrants (since they each have unique zoom link; easily lost in earlier email)
- [x] ask speakers about their favorite pump-up song/a song that we'll play at the intro
- [x] create intro slides
- [x] call takes place
- [x] update Event page - event past
- [x] publish blog post & promote
- [x] add post link to Event page

**Comment by jules32** [comment]
Woohoo!

**Comment by jules32** [comment]
@stefaniebutland , would you be able to make the Events Page next week so we can link to it in the Newsletter? I will revisit/draft the Newsletter by early next week so we can send :)

**Comment by jules32** [comment]
Ah, I am realizing we were thinking Sept 16 for the newsletter, maybe we should shift to Sept 11 or 12 now that we have the Community Call date?

**Comment by stefaniebutland** [comment]
@jules32 Waiting to hear from Ileana. Date not confirmed.
Could say "stay tuned for September comm call, Openscapes Goes to the White House"

**Comment by jules32** [comment]
Great, we can check in after confirmation and share it in the Newsletter accordingly. Thanks!

**Comment by stefaniebutland** [comment]
@jules32, Ileana confirmed she is available, do you have a preference:
~Tuesday~ Thursday, September 26, 2024
Proposed Time a): 12-1 pm PT / 3-4 pm ET / 9-10 am HT
Proposed Time b): 1-2 pm PT / 4-5 pm ET / 10-11 am HT
Trying to keep our Hawaii-located NMFS Openscapes friends in mind

**Comment by stefaniebutland** [comment]
sent calendar invite to Ileana & Julie for Thursday, September 26, **1-2 pm PT** / 4-5 pm ET / 10-11 am HT.
No conflicts with NMFS Open Science calendar

**Comment by jules32** [comment]
Yay, so excited!!

**Comment by jules32** [comment]
@stefaniebutland 

official language: Openscapes is being recognized at the "Celebration of the OSTP Year of Open Science Recognition Challenge Winners" at The White House

**Comment by stefaniebutland** [comment]
Posted to Slacks:

- Openscapes
- CSCCE
- rOpenSci
- FTS
- RLadies organizers
- RLadies community
- SOSS Standard Office Space Kamloops
- Built in Kamloops

:mega: Community Call: Openscapes Goes to The White House!
Thursday, September 26, 2024, 1 - 2 pm PT ([find your local time](https://www.timeanddate.com/worldclock/fixedtime.html?msg=Community+Call%3A+Openscapes+Goes+to+the+White+House&iso=20240926T13&p1=1050&ah=1))
[Read more and register (free)](https://openscapes.org/events/2024-09-26-openscapes-whitehouse/)
Openscapes is being recognized at the “Celebration of the OSTP Year of Open Science Recognition Challenge Winners” at The White House and we want to share the joy! In this Community Call, [Julie Lowndes & Ileana Fenwick](https://openscapes.org/team) will interview each other to share their excitement, some anxiousness, and their experiences. Why was Openscapes recognized? Who else was there? How did you prepare? What do you want to ask them?

[Posted to Stef's LinkedIn](https://www.linkedin.com/posts/stefaniebutland_community-call-openscapes-goes-to-the-white-activity-7240078997475237888-AlBA?utm_source=share&utm_medium=member_desktop) and to Openscapes Mastodon & Bluesky
 
alt txt for white house image: Official white graphic of The White House on a blue background. Text below in white says The White House, Washington

![Image](https://github.com/user-attachments/assets/72eeffd0-1981-472d-a348-95215b8d1aad)

**Comment by stefaniebutland** [comment]
@jules32 please post to ESIP & TOPS Slacks & your LinkedIn cc @IleanaF

I'll replied to Allison Mills email to share this

**Comment by stefaniebutland** [comment]
Started Agenda doc: [OpenscapesCommunityCall_WhiteHouse_2024-09-26](https://docs.google.com/document/d/1SQrGuMmhc4FDjdihJbkv5uCW4_0uoRjVQui_D9QEVAs/edit) ready for @jules32 & @ileanaF to add questions to ask each other

**Comment by jules32** [comment]
Thank you @stefaniebutland ! I added a few notes for the conversation and will continue to as I think of them :)

**Comment by jules32** [comment]
I added starter blog post text at the bottom of the agenda doc.

**Comment by jules32** [comment]
@stefaniebutland blog post is ready for posting!

**Comment by stefaniebutland** [comment]
Published https://openscapes.org/blog/2024-10-03-openscapes-recognized-white-house/
cross posted to NASA, NMFS, Pathways
Bluesky, Mastodon
