### ISSUE TITLE
Dec 9 Community Call - Open Leadership w/ Abby Cabunoc Mayes

### ISSUE THREAD

**Issue by jules32** [Openscapes/how_we_work#90]
**Date:** Dec 9, 2021
**Time:** 10-11am, Pacific Time
**Location:** Zoom, (via eventbrite registration)

## Overview
(updated/iterated Oct 28)

An Open Leadership Chat with Abby Cabunoc Mayes & others. Casual conversation with Abby to discuss Open Leaders and supporting open leaders. The conversation will be in the [Celebrity-interview](https://www.liberatingstructures.com/22-celebrity-interview/) style. 

Potential questions/ideas (to iterate and add!) 

- Design of Open Leaders blends a lot of things: facilitating group learning, adult learners that want to work on their own projects, new tech (github) but also tech agnostic, safety, inclusion. Can you talk a bit about how you first created Open Leaders, and how you iterated?
- Scaling Open Leaders as a program, letting go ownership, tension of open & freely available but not invisible labor and attribution?

In conversation, give background of OL, Openscapes Champions, and other programs

What does Abby want to be sure to talk about?

## Agenda

Times PT

- 9:40 - sign into Zoom to setup/check audio etc
- 9:55 - start rotating slides and letting people in Zoom
    - one slide says we'll start at at :02 after, say hello in Chat
- 10:00 - start pump up music, slides keep rotating
- 10:02 - welcome (Erin)
- 10:05 - Celebrity Interview with Abby & Chad
- 10:30 - Other OLx Community Shares - program background & 1 iteration (~5 mins each, incl. discussion)
    - Open Life Science, Open Hardware
- 10:45 - Participant Q&A (Julie curated)
- 10:50 - closing & thank you
- 10:55 - end

Examples of previous Openscapes Community Calls: https://www.openscapes.org/tags/community-call/

## TODO

- [x] create page at https://openscapes.org/events
- [x] set up eventbrite page with registration, ~ Nov 1
- [x] tweet announcement ~Nov 1
- [ ] tweet reminder ~Dec 1 and Dec 8
- [ ] ask Abby about her favorite pump-up song/a song she likes that we'll play at the intro
- [ ] create slides

**Comment by jules32** [comment]
Draft is up at https://openscapes.org/events; will tweet once Abby and Chad have reviewed

**Comment by jules32** [comment]
Posted and tweeted! https://twitter.com/openscapes/status/1455981851697319937

**Comment by jules32** [comment]
[Agenda Google Doc](https://docs.google.com/document/d/1epegLSAZcfzAXTmSrj9zgea1-90Fg1dFRo-PNl0T6W0/edit?usp=sharing)

**Comment by erinmr** [comment]
Looks super!

**Comment by jules32** [comment]
Woohoo! I've just shared with Abby, Chad, Malvika, Yo, Beth, Bo, and Andre too. Excited!

**Comment by jules32** [comment]
[Slides](https://docs.google.com/presentation/d/1h0eLI7TKcEqg0ob84NlkQ_-N9uMW5FY7IPfOy-Vuv7s/edit#slide=id.gc55b224ab0_0_1) are ready to go! 

And @acabunoc ! I forgot an important thing - what is a song that you'd like to play while we wait to get started? Could be pump-up, calming, whatever you fancy :)

**Comment by acabunoc** [comment]
This is a very tough decision! I’ve been listening to Christmas music on repeat for the past week and I’ve forgotten about everything else…

I really liked those chill beats Arne played at the CZI event. Maybe I’ll try to find the playlist he shared

**Comment by acabunoc** [comment]
https://www.youtube.com/watch?v=5qap5aO4i9A

**Comment by jules32** [comment]
Great choice! Thanks Abby :)

**Comment by jules32** [comment]
Thanks All! ❤️ 

Talk now on youtube!
https://www.youtube.com/watch?v=rsd4z8kXJgo
